//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

namespace CIXClient.Models
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true, Namespace="http://cixonline.com")]
    [XmlRoot(Namespace="http://cixonline.com", IsNullable=false)]
    public partial class StarSet {
    
        private string countField;
    
        private string startField;
    
        private StarSetStarsStar[] starsField;
    
        /// <remarks/>
        public string Count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
            }
        }
    
        /// <remarks/>
        public string Start {
            get {
                return this.startField;
            }
            set {
                this.startField = value;
            }
        }
    
        /// <remarks/>
        [XmlArrayItem("Star", typeof(StarSetStarsStar), IsNullable=false)]
        public StarSetStarsStar[] Stars {
            get {
                return this.starsField;
            }
            set {
                this.starsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true, Namespace="http://cixonline.com")]
    public partial class StarSetStarsStar {
    
        private string authorField;
    
        private string confField;
    
        private int msgIDField;
    
        private string postedDateField;
    
        private string subjectField;
    
        private string topicField;
    
        private string starIDField;
    
        /// <remarks/>
        public string Author {
            get {
                return this.authorField;
            }
            set {
                this.authorField = value;
            }
        }
    
        /// <remarks/>
        public string Conf {
            get {
                return this.confField;
            }
            set {
                this.confField = value;
            }
        }
    
        /// <remarks/>
        public int MsgID {
            get {
                return this.msgIDField;
            }
            set {
                this.msgIDField = value;
            }
        }
    
        /// <remarks/>
        public string PostedDate {
            get {
                return this.postedDateField;
            }
            set {
                this.postedDateField = value;
            }
        }
    
        /// <remarks/>
        public string Subject {
            get {
                return this.subjectField;
            }
            set {
                this.subjectField = value;
            }
        }
    
        /// <remarks/>
        public string Topic {
            get {
                return this.topicField;
            }
            set {
                this.topicField = value;
            }
        }
    
        /// <remarks/>
        public string starID {
            get {
                return this.starIDField;
            }
            set {
                this.starIDField = value;
            }
        }
    }
}