//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CIXReader.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CIXReader.Properties.Resources_Mono", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ActiveStar {
            get {
                object obj = ResourceManager.GetObject("ActiveStar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Categories.
        /// </summary>
        internal static string AllCategories {
            get {
                return ResourceManager.GetString("AllCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CIXReader.
        /// </summary>
        internal static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ArtsCategory {
            get {
                object obj = ResourceManager.GetObject("ArtsCategory", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As &amp;Ignored.
        /// </summary>
        internal static string AsIgnored {
            get {
                return ResourceManager.GetString("AsIgnored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As N&amp;ormal.
        /// </summary>
        internal static string AsNormal {
            get {
                return ResourceManager.GetString("AsNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As Pri&amp;ority.
        /// </summary>
        internal static string AsPriority {
            get {
                return ResourceManager.GetString("AsPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As &amp;Read.
        /// </summary>
        internal static string AsRead {
            get {
                return ResourceManager.GetString("AsRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As Un&amp;ignored.
        /// </summary>
        internal static string AsUnignored {
            get {
                return ResourceManager.GetString("AsUnignored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As Un&amp;read.
        /// </summary>
        internal static string AsUnread {
            get {
                return ResourceManager.GetString("AsUnread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username or password.
        /// </summary>
        internal static string BadUsernameOrPassword {
            get {
                return ResourceManager.GetString("BadUsernameOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic.
        /// </summary>
        internal static string Basic {
            get {
                return ResourceManager.GetString("Basic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beta.
        /// </summary>
        internal static string Beta {
            get {
                return ResourceManager.GetString("Beta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to the CIXReader beta forum.
        /// </summary>
        internal static string BetaTooltip {
            get {
                return ResourceManager.GetString("BetaTooltip", resourceCulture);
            }
        }
        
		/// <summary>
		///   Looks up a localized string similar to All existing messages and any new messages from {0} will automatically be marked as read. Are you sure?.
		/// </summary>
		internal static string BlockPrompt {
			get {
				return ResourceManager.GetString("BlockPrompt", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Block all messages from {0}.
		/// </summary>
		internal static string BlockTitle {
			get {
				return ResourceManager.GetString("BlockTitle", resourceCulture);
			}
		}

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Bubble {
            get {
                object obj = ResourceManager.GetObject("Bubble", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BusinessCategory {
            get {
                object obj = ResourceManager.GetObject("BusinessCategory", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to close this message without sending it?.
        /// </summary>
        internal static string CancelNewMessagePrompt {
            get {
                return ResourceManager.GetString("CancelNewMessagePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Message.
        /// </summary>
        internal static string CancelNewMessageTitle {
            get {
                return ResourceManager.GetString("CancelNewMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot open {0} : {1}.
        /// </summary>
        internal static string CannotOpen {
            get {
                return ResourceManager.GetString("CannotOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Categories {
            get {
                object obj = ResourceManager.GetObject("Categories", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Chat {
            get {
                object obj = ResourceManager.GetObject("Chat", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CIXCategory {
            get {
                object obj = ResourceManager.GetObject("CIXCategory", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CIXLogo2 {
            get {
                object obj = ResourceManager.GetObject("CIXLogo2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon CixReader {
            get {
                object obj = ResourceManager.GetObject("CixReader", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CIXReaderLogo {
            get {
                object obj = ResourceManager.GetObject("CIXReaderLogo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear &amp;Flag.
        /// </summary>
        internal static string ClearFlag {
            get {
                return ResourceManager.GetString("ClearFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Read &amp;Lock.
        /// </summary>
        internal static string ClearReadLock {
            get {
                return ResourceManager.GetString("ClearReadLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Close.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CloseButton {
            get {
                object obj = ResourceManager.GetObject("CloseButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Closed {
            get {
                object obj = ResourceManager.GetObject("Closed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed.
        /// </summary>
        internal static string ClosedForum {
            get {
                return ResourceManager.GetString("ClosedForum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close the search bar.
        /// </summary>
        internal static string CloseSearchBar {
            get {
                return ResourceManager.GetString("CloseSearchBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CollapseArrow {
            get {
                object obj = ResourceManager.GetObject("CollapseArrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reply.
        /// </summary>
        internal static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ComputersCategory {
            get {
                object obj = ResourceManager.GetObject("ComputersCategory", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Confidential {
            get {
                object obj = ResourceManager.GetObject("Confidential", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the {0} folder?.
        /// </summary>
        internal static string ConfirmDelete {
            get {
                return ResourceManager.GetString("ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to join the {0} forum?.
        /// </summary>
        internal static string ConfirmJoin {
            get {
                return ResourceManager.GetString("ConfirmJoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to resign from {0} ?.
        /// </summary>
        internal static string ConfirmResign {
            get {
                return ResourceManager.GetString("ConfirmResign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Withdraw this message from the server?.
        /// </summary>
        internal static string ConfirmWithdraw {
            get {
                return ResourceManager.GetString("ConfirmWithdraw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Control {
            get {
                object obj = ResourceManager.GetObject("Control", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link to message copied to clipboard.
        /// </summary>
        internal static string CopyLinkInfoMessage {
            get {
                return ResourceManager.GetString("CopyLinkInfoMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search in the current forum.
        /// </summary>
        internal static string CurrentForumSearch {
            get {
                return ResourceManager.GetString("CurrentForumSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search in the current topic.
        /// </summary>
        internal static string CurrentTopicSearch {
            get {
                return ResourceManager.GetString("CurrentTopicSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        internal static string Custom {
            get {
                return ResourceManager.GetString("Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customise Toolbar.
        /// </summary>
        internal static string CustomiseToolbar {
            get {
                return ResourceManager.GetString("CustomiseToolbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ameol
        ///CIX
        ///CIXReader.
        /// </summary>
        internal static string CustomWords {
            get {
                return ResourceManager.GetString("CustomWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily.
        /// </summary>
        internal static string Daily {
            get {
                return ResourceManager.GetString("Daily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        internal static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DeleteButton {
            get {
                object obj = ResourceManager.GetObject("DeleteButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete this conversation?.
        /// </summary>
        internal static string DeleteConversation {
            get {
                return ResourceManager.GetString("DeleteConversation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Folder.
        /// </summary>
        internal static string DeleteFolder {
            get {
                return ResourceManager.GetString("DeleteFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Delete.
        /// </summary>
        internal static string DeleteOnMenu {
            get {
                return ResourceManager.GetString("DeleteOnMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory.
        /// </summary>
        internal static string Directory {
            get {
                return ResourceManager.GetString("Directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display the CIX Forums directory.
        /// </summary>
        internal static string DirectoryTooltip {
            get {
                return ResourceManager.GetString("DirectoryTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap downArrow {
            get {
                object obj = ResourceManager.GetObject("downArrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Draft {
            get {
                object obj = ResourceManager.GetObject("Draft", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drafts.
        /// </summary>
        internal static string DraftText {
            get {
                return ResourceManager.GetString("DraftText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Error1 {
            get {
                object obj = ResourceManager.GetObject("Error1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\adeflang1025\ansi\ansicpg1252\uc1\adeff0\deff0\stshfdbch31505\stshfloch31506\stshfhich31506\stshfbi0\deflang2057\deflangfe2057\themelang2057\themelangfe0\themelangcs0{\fonttbl{\f0\fbidi \froman\fcharset0\fprq2{\*\panose 02020603050405020304}Times New Roman;}{\f34\fbidi \froman\fcharset0\fprq2{\*\panose 02040503050406030204}Cambria Math;}
        ///{\f39\fbidi \fswiss\fcharset0\fprq2{\*\panose 00000000000000000000}Verdana Ref;}{\flomajor\f31500\fbidi \froman\fcharset0\fprq2{\*\panose 02020603050405020304}Times [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EULA {
            get {
                return ResourceManager.GetString("EULA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ExpandArrow {
            get {
                object obj = ResourceManager.GetObject("ExpandArrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand this thread.
        /// </summary>
        internal static string ExpandThread {
            get {
                return ResourceManager.GetString("ExpandThread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Flag.
        /// </summary>
        internal static string Flag {
            get {
                return ResourceManager.GetString("Flag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This topic is read-only. You cannot post or comment to messages in it..
        /// </summary>
        internal static string FolderIsReadOnly {
            get {
                return ResourceManager.GetString("FolderIsReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forums.
        /// </summary>
        internal static string Forums {
            get {
                return ResourceManager.GetString("Forums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display CIX forums.
        /// </summary>
        internal static string ForumsTooltip {
            get {
                return ResourceManager.GetString("ForumsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full.
        /// </summary>
        internal static string Full {
            get {
                return ResourceManager.GetString("Full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GamesCategory {
            get {
                object obj = ResourceManager.GetObject("GamesCategory", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GeneralPrefImage {
            get {
                object obj = ResourceManager.GetObject("GeneralPrefImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message {0} not found in this topic.
        /// </summary>
        internal static string GotoError {
            get {
                return ResourceManager.GetString("GotoError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap HealthCategory {
            get {
                object obj = ResourceManager.GetObject("HealthCategory", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Status &amp;Bar.
        /// </summary>
        internal static string HideStatusBar {
            get {
                return ResourceManager.GetString("HideStatusBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Hide Toolbar.
        /// </summary>
        internal static string HideToolBar {
            get {
                return ResourceManager.GetString("HideToolBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap HomeCategory {
            get {
                object obj = ResourceManager.GetObject("HomeCategory", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore.
        /// </summary>
        internal static string Ignore {
            get {
                return ResourceManager.GetString("Ignore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This message and all replies are ignored..
        /// </summary>
        internal static string IgnoredMessage {
            get {
                return ResourceManager.GetString("IgnoredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This account has not yet been activated.
        /// </summary>
        internal static string InactivatedAccount {
            get {
                return ResourceManager.GetString("InactivatedAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap InactiveStar {
            get {
                object obj = ResourceManager.GetObject("InactiveStar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Inbox {
            get {
                object obj = ResourceManager.GetObject("Inbox", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inbox.
        /// </summary>
        internal static string InboxName {
            get {
                return ResourceManager.GetString("InboxName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is a closed forum. You need to contact the forum moderator to request access. Do you want to send a request message now?.
        /// </summary>
        internal static string JoinClosed {
            get {
                return ResourceManager.GetString("JoinClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This forum is closed. To join the forum, you need to contact the moderators to request admittance.
        /// </summary>
        internal static string JoinClosedForum {
            get {
                return ResourceManager.GetString("JoinClosedForum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to join the forum. The forum may be closed or you may have reached the limit on the number of forums you can join.
        /// </summary>
        internal static string JoinFailure {
            get {
                return ResourceManager.GetString("JoinFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join Forum.
        /// </summary>
        internal static string JoinForum {
            get {
                return ResourceManager.GetString("JoinForum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By clicking Join This Forum, you will be added to the forum participant list and you will be able to read and post to any topic in the forum..
        /// </summary>
        internal static string JoinForumStatusText {
            get {
                return ResourceManager.GetString("JoinForumStatusText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This forum does not exist in the directory. Check the spelling of the name..
        /// </summary>
        internal static string JoinNoSuchForum {
            get {
                return ResourceManager.GetString("JoinNoSuchForum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CIXReader will join this forum when you next go online..
        /// </summary>
        internal static string JoinPending {
            get {
                return ResourceManager.GetString("JoinPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Key {
            get {
                object obj = ResourceManager.GetObject("Key", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap KidsCategory {
            get {
                object obj = ResourceManager.GetObject("KidsCategory", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last on {0}.
        /// </summary>
        internal static string LastOnText {
            get {
                return ResourceManager.GetString("LastOnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is the latest version of CIXReader.
        /// </summary>
        internal static string LatestVersion {
            get {
                return ResourceManager.GetString("LatestVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string LatestVersionTitle {
            get {
                return ResourceManager.GetString("LatestVersionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to copy a link to this message to the clipboard.
        /// </summary>
        internal static string LinkTooltip {
            get {
                return ResourceManager.GetString("LinkTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location: {0}.
        /// </summary>
        internal static string LocationText {
            get {
                return ResourceManager.GetString("LocationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Mail {
            get {
                object obj = ResourceManager.GetObject("Mail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Forum.
        /// </summary>
        internal static string ManageForum {
            get {
                return ResourceManager.GetString("ManageForum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ManageGeneral {
            get {
                object obj = ResourceManager.GetObject("ManageGeneral", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ManageMods {
            get {
                object obj = ResourceManager.GetObject("ManageMods", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ManageParts {
            get {
                object obj = ResourceManager.GetObject("ManageParts", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} replies.
        /// </summary>
        internal static string ManyReplies {
            get {
                return ResourceManager.GetString("ManyReplies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Map {
            get {
                object obj = ResourceManager.GetObject("Map", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark all messages in {0} read?.
        /// </summary>
        internal static string MarkFolderRead {
            get {
                return ResourceManager.GetString("MarkFolderRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MarkRead {
            get {
                object obj = ResourceManager.GetObject("MarkRead", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MenuDropBlue {
            get {
                object obj = ResourceManager.GetObject("MenuDropBlue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MenuDropWhite {
            get {
                object obj = ResourceManager.GetObject("MenuDropWhite", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message will be retrieved from the server when you next go online..
        /// </summary>
        internal static string MessageRetrievePending {
            get {
                return ResourceManager.GetString("MessageRetrievePending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moderators.
        /// </summary>
        internal static string Moderators {
            get {
                return ResourceManager.GetString("Moderators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MoneyCategory {
            get {
                object obj = ResourceManager.GetObject("MoneyCategory", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Files|*.jpg;*.gif;*.png|JPEG Files|*.jpg|GIF Files|*.gif|PNG Files|*.png|All files (*.*)|*.*.
        /// </summary>
        internal static string MugshotFileTypes {
            get {
                return ResourceManager.GetString("MugshotFileTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Never.
        /// </summary>
        internal static string Never {
            get {
                return ResourceManager.GetString("Never", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Message in {0} • {1}.
        /// </summary>
        internal static string NewMessageTitle {
            get {
                return ResourceManager.GetString("NewMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New PMessage.
        /// </summary>
        internal static string NewPMessage {
            get {
                return ResourceManager.GetString("NewPMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NewsCategory {
            get {
                object obj = ResourceManager.GetObject("NewsCategory", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot connect to CIX.Check your internet connection..
        /// </summary>
        internal static string NoConnection {
            get {
                return ResourceManager.GetString("NoConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        internal static string Normal {
            get {
                return ResourceManager.GetString("Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string NoSignature {
            get {
                return ResourceManager.GetString("NoSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (No subject).
        /// </summary>
        internal static string NoSubject {
            get {
                return ResourceManager.GetString("NoSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offline.
        /// </summary>
        internal static string Offline {
            get {
                return ResourceManager.GetString("Offline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 reply.
        /// </summary>
        internal static string OneReply {
            get {
                return ResourceManager.GetString("OneReply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users who are online now.
        /// </summary>
        internal static string OnlineUsers {
            get {
                return ResourceManager.GetString("OnlineUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string OpenForum {
            get {
                return ResourceManager.GetString("OpenForum", resourceCulture);
            }
        }

		/// <summary>
		///   Looks up a localized string similar to Operator.
		/// </summary>
		internal static string Operator {
			get {
				return ResourceManager.GetString("Operator", resourceCulture);
			}
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Outbox.
        /// </summary>
        internal static string OutboxText {
            get {
                return ResourceManager.GetString("OutboxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can only comment to your own messages in this topic..
        /// </summary>
        internal static string OwnerPostingOnly {
            get {
                return ResourceManager.GetString("OwnerPostingOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participants.
        /// </summary>
        internal static string Participants {
            get {
                return ResourceManager.GetString("Participants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} participants.
        /// </summary>
        internal static string ParticipantsCount {
            get {
                return ResourceManager.GetString("ParticipantsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participants in {0}.
        /// </summary>
        internal static string ParticipantsTitle {
            get {
                return ResourceManager.GetString("ParticipantsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PMessages.
        /// </summary>
        internal static string PMessages {
            get {
                return ResourceManager.GetString("PMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display your private messages.
        /// </summary>
        internal static string PMessagesTooltip {
            get {
                return ResourceManager.GetString("PMessagesTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error printing document: {0}.
        /// </summary>
        internal static string PrintError {
            get {
                return ResourceManager.GetString("PrintError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date: {0}.
        /// </summary>
        internal static string PrintMailDate {
            get {
                return ResourceManager.GetString("PrintMailDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From: {0}.
        /// </summary>
        internal static string PrintMailFrom {
            get {
                return ResourceManager.GetString("PrintMailFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject: {0}.
        /// </summary>
        internal static string PrintMailSubject {
            get {
                return ResourceManager.GetString("PrintMailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority.
        /// </summary>
        internal static string Priority {
            get {
                return ResourceManager.GetString("Priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private.
        /// </summary>
        internal static string PrivateForum {
            get {
                return ResourceManager.GetString("PrivateForum", resourceCulture);
            }
        }

		/// <summary>
		///   Looks up a localized string similar to Property.
		/// </summary>
		internal static string Property {
			get {
				return ResourceManager.GetString("Property", resourceCulture);
			}
		}
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ReadLock {
            get {
                object obj = ResourceManager.GetObject("ReadLock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ReadMessage {
            get {
                object obj = ResourceManager.GetObject("ReadMessage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ReferenceCategory {
            get {
                object obj = ResourceManager.GetObject("ReferenceCategory", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh {0}.
        /// </summary>
        internal static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }

		/// <summary>
		///   Looks up a localized string similar to Refresh.
		/// </summary>
		internal static string RefreshText {
			get {
				return ResourceManager.GetString("RefreshText", resourceCulture);
			}
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Reject.
        /// </summary>
        internal static string Reject {
            get {
                return ResourceManager.GetString("Reject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Remove.
        /// </summary>
        internal static string RemoveButton {
            get {
                return ResourceManager.GetString("RemoveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replying to {0}.
        /// </summary>
        internal static string ReplyEditorTitle {
            get {
                return ResourceManager.GetString("ReplyEditorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reply to {0} in {1} • {2}.
        /// </summary>
        internal static string ReplyTitle {
            get {
                return ResourceManager.GetString("ReplyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reply to message {0}.
        /// </summary>
        internal static string ReplyToMessage {
            get {
                return ResourceManager.GetString("ReplyToMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Request Admittance.
        /// </summary>
        internal static string RequestAdmittance {
            get {
                return ResourceManager.GetString("RequestAdmittance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
		/// <summary>
		///   Looks up a localized string similar to This will reset all rules back to the CIXReader defaults and discard all custom modifications. Are you sure?.
		/// </summary>
		internal static string ResetRules {
			get {
				return ResourceManager.GetString("ResetRules", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Reset All Rules.
		/// </summary>
		internal static string ResetRulesTitle {
			get {
				return ResourceManager.GetString("ResetRulesTitle", resourceCulture);
			}
		}

        /// <summary>
        ///   Looks up a localized string similar to Resign {0}.
        /// </summary>
        internal static string Resign {
            get {
                return ResourceManager.GetString("Resign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resign Forum.
        /// </summary>
        internal static string ResignForum {
            get {
                return ResourceManager.GetString("ResignForum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CIXReader will resign this forum when you next go online..
        /// </summary>
        internal static string ResignPending {
            get {
                return ResourceManager.GetString("ResignPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Restore.
        /// </summary>
        internal static string RestoreButton {
            get {
                return ResourceManager.GetString("RestoreButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieve.
        /// </summary>
        internal static string Retrieve {
            get {
                return ResourceManager.GetString("Retrieve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will delete any custom theme file and revert to the CIXReader default. Are you sure?.
        /// </summary>
        internal static string RevertThemeToDefault {
            get {
                return ResourceManager.GetString("RevertThemeToDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rightArrow {
            get {
                object obj = ResourceManager.GetObject("rightArrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ROTopic {
            get {
                object obj = ResourceManager.GetObject("ROTopic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap rulesPreferences {
			get {
				object obj = ResourceManager.GetObject("rulesPreferences", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ScienceCategory {
            get {
                object obj = ResourceManager.GetObject("ScienceCategory", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Script {
            get {
                object obj = ResourceManager.GetObject("Script", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script Exception.
        /// </summary>
        internal static string ScriptException {
            get {
                return ResourceManager.GetString("ScriptException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error installing script. Check the log file for more details..
        /// </summary>
        internal static string ScriptInstallError {
            get {
                return ResourceManager.GetString("ScriptInstallError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Search2 {
            get {
                object obj = ResourceManager.GetObject("Search2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;SearchEnginesFile&gt;
        ///  &lt;Site name=&quot;Google&quot; link=&quot;http://www.google.com/search?q={0}&quot; /&gt;
        ///  &lt;Site name=&quot;Bing&quot; link=&quot;http://www.bing.com/search?q={0}&quot; /&gt;
        ///  &lt;Site name=&quot;Yahoo&quot; link=&quot;http://search.yahoo.com/search?p={0}&quot; /&gt;
        ///&lt;/SearchEnginesFile&gt;.
        /// </summary>
        internal static string SearchEngines {
            get {
                return ResourceManager.GetString("SearchEngines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for....
        /// </summary>
        internal static string SearchForText {
            get {
                return ResourceManager.GetString("SearchForText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search in {0}.
        /// </summary>
        internal static string SearchForTextIn {
            get {
                return ResourceManager.GetString("SearchForTextIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search in {0}.
        /// </summary>
        internal static string SearchIn {
            get {
                return ResourceManager.GetString("SearchIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search With {0}.
        /// </summary>
        internal static string SearchWith {
            get {
                return ResourceManager.GetString("SearchWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a Mugshot File.
        /// </summary>
        internal static string SelectMugshot {
            get {
                return ResourceManager.GetString("SelectMugshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Read &amp;Lock.
        /// </summary>
        internal static string SetReadLock {
            get {
                return ResourceManager.GetString("SetReadLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forum.
        /// </summary>
        internal static string SForum {
            get {
                return ResourceManager.GetString("SForum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share.
        /// </summary>
        internal static string Share {
            get {
                return ResourceManager.GetString("Share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ShoppingCategory {
            get {
                object obj = ResourceManager.GetObject("ShoppingCategory", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Status &amp;Bar.
        /// </summary>
        internal static string ShowStatusBar {
            get {
                return ResourceManager.GetString("ShowStatusBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S&amp;how Toolbar.
        /// </summary>
        internal static string ShowToolBar {
            get {
                return ResourceManager.GetString("ShowToolBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SignaturePreferences {
            get {
                object obj = ResourceManager.GetObject("SignaturePreferences", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SmallDownArrow {
            get {
                object obj = ResourceManager.GetObject("SmallDownArrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SmallFolder {
            get {
                object obj = ResourceManager.GetObject("SmallFolder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SmartFolder {
            get {
                object obj = ResourceManager.GetObject("SmartFolder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SocietyCategory {
            get {
                object obj = ResourceManager.GetObject("SocietyCategory", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SportsCategory {
            get {
                object obj = ResourceManager.GetObject("SportsCategory", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starred.
        /// </summary>
        internal static string Starred {
            get {
                return ResourceManager.GetString("Starred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started at {0}.
        /// </summary>
        internal static string StartedAt {
            get {
                return ResourceManager.GetString("StartedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started by {0}.
        /// </summary>
        internal static string StartedBy {
            get {
                return ResourceManager.GetString("StartedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refreshing private messages....
        /// </summary>
        internal static string StatusInboxRefresh {
            get {
                return ResourceManager.GetString("StatusInboxRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posting message &quot;{0}&quot;.
        /// </summary>
        internal static string StatusMessagePost {
            get {
                return ResourceManager.GetString("StatusMessagePost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refreshing....
        /// </summary>
        internal static string StatusTopicRefresh {
            get {
                return ResourceManager.GetString("StatusTopicRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topic.
        /// </summary>
        internal static string STopic {
            get {
                return ResourceManager.GetString("STopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support.
        /// </summary>
        internal static string Support {
            get {
                return ResourceManager.GetString("Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to the CIXReader Support forum.
        /// </summary>
        internal static string SupportTooltip {
            get {
                return ResourceManager.GetString("SupportTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Topic {
            get {
                object obj = ResourceManager.GetObject("Topic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Threads.
        /// </summary>
        internal static string TopThreads {
            get {
                return ResourceManager.GetString("TopThreads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TravelCategory {
            get {
                object obj = ResourceManager.GetObject("TravelCategory", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo {0}.
        /// </summary>
        internal static string Undo {
            get {
                return ResourceManager.GetString("Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unignore.
        /// </summary>
        internal static string Unignore {
            get {
                return ResourceManager.GetString("Unignore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This message could not be posted. The recipient is unknown..
        /// </summary>
        internal static string UnknownRecipientError {
            get {
                return ResourceManager.GetString("UnknownRecipientError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UnreadMessage {
            get {
                object obj = ResourceManager.GetObject("UnreadMessage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UnreadPriorityMessage {
            get {
                object obj = ResourceManager.GetObject("UnreadPriorityMessage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UpdatePreferences {
            get {
                object obj = ResourceManager.GetObject("UpdatePreferences", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        internal static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }

		/// <summary>
		///   Looks up a localized string similar to Value.
		/// </summary>
		internal static string Value {
			get {
				return ResourceManager.GetString("Value", resourceCulture);
			}
		}
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ViewingPrefImage {
            get {
                object obj = ResourceManager.GetObject("ViewingPrefImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Warning {
            get {
                object obj = ResourceManager.GetObject("Warning", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekly.
        /// </summary>
        internal static string Weekly {
            get {
                return ResourceManager.GetString("Weekly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CIXReader is the new way to access CIX Forums on your Windows Desktop and read messages either off-line or on-line. Allows instant and draft postings, immediate access to whole topics, forums and automatically keeps in sync with the CIX Forums web interface..
        /// </summary>
        internal static string WelcomeSubtitle {
            get {
                return ResourceManager.GetString("WelcomeSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to CIXReader.
        /// </summary>
        internal static string WelcomeTitle {
            get {
                return ResourceManager.GetString("WelcomeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Withdraw.
        /// </summary>
        internal static string Withdraw {
            get {
                return ResourceManager.GetString("Withdraw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Withdraw.
        /// </summary>
        internal static string WithdrawOnMenu {
            get {
                return ResourceManager.GetString("WithdrawOnMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xmpp:{0}@cix.
        /// </summary>
        internal static string XMPPLink {
            get {
                return ResourceManager.GetString("XMPPLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script Packages (*.zip)|*.zip|All files (*.*)|*.*.
        /// </summary>
        internal static string ZipFileExtension {
            get {
                return ResourceManager.GetString("ZipFileExtension", resourceCulture);
            }
        }
    }
}
