//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CIXReader.Properties {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("CIXReader.Properties.Resources_Mono", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        internal static string CancelNewMessagePrompt {
            get {
                return ResourceManager.GetString("CancelNewMessagePrompt", resourceCulture);
            }
        }
        
        internal static string CancelNewMessageTitle {
            get {
                return ResourceManager.GetString("CancelNewMessageTitle", resourceCulture);
            }
        }
        
        internal static string PMessages {
            get {
                return ResourceManager.GetString("PMessages", resourceCulture);
            }
        }
        
        internal static string Offline {
            get {
                return ResourceManager.GetString("Offline", resourceCulture);
            }
        }
        
        internal static string SelectMugshot {
            get {
                return ResourceManager.GetString("SelectMugshot", resourceCulture);
            }
        }
        
        internal static string MugshotFileTypes {
            get {
                return ResourceManager.GetString("MugshotFileTypes", resourceCulture);
            }
        }
        
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        internal static string ConfirmJoin {
            get {
                return ResourceManager.GetString("ConfirmJoin", resourceCulture);
            }
        }
        
        internal static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap downArrow {
            get {
                object obj = ResourceManager.GetObject("downArrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap rightArrow {
            get {
                object obj = ResourceManager.GetObject("rightArrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Topic {
            get {
                object obj = ResourceManager.GetObject("Topic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static string Forums {
            get {
                return ResourceManager.GetString("Forums", resourceCulture);
            }
        }
        
        internal static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Categories {
            get {
                object obj = ResourceManager.GetObject("Categories", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ArtsCategory {
            get {
                object obj = ResourceManager.GetObject("ArtsCategory", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BusinessCategory {
            get {
                object obj = ResourceManager.GetObject("BusinessCategory", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CIXCategory {
            get {
                object obj = ResourceManager.GetObject("CIXCategory", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ComputersCategory {
            get {
                object obj = ResourceManager.GetObject("ComputersCategory", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GamesCategory {
            get {
                object obj = ResourceManager.GetObject("GamesCategory", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HealthCategory {
            get {
                object obj = ResourceManager.GetObject("HealthCategory", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HomeCategory {
            get {
                object obj = ResourceManager.GetObject("HomeCategory", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap KidsCategory {
            get {
                object obj = ResourceManager.GetObject("KidsCategory", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MoneyCategory {
            get {
                object obj = ResourceManager.GetObject("MoneyCategory", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NewsCategory {
            get {
                object obj = ResourceManager.GetObject("NewsCategory", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ReferenceCategory {
            get {
                object obj = ResourceManager.GetObject("ReferenceCategory", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ScienceCategory {
            get {
                object obj = ResourceManager.GetObject("ScienceCategory", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ShoppingCategory {
            get {
                object obj = ResourceManager.GetObject("ShoppingCategory", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SocietyCategory {
            get {
                object obj = ResourceManager.GetObject("SocietyCategory", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SportsCategory {
            get {
                object obj = ResourceManager.GetObject("SportsCategory", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TravelCategory {
            get {
                object obj = ResourceManager.GetObject("TravelCategory", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        internal static string Ignore {
            get {
                return ResourceManager.GetString("Ignore", resourceCulture);
            }
        }
        
        internal static string Priority {
            get {
                return ResourceManager.GetString("Priority", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap ReadMessage {
            get {
                object obj = ResourceManager.GetObject("ReadMessage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap UnreadMessage {
            get {
                object obj = ResourceManager.GetObject("UnreadMessage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        internal static string Retrieve {
            get {
                return ResourceManager.GetString("Retrieve", resourceCulture);
            }
        }
        
        internal static string MessageRetrievePending {
            get {
                return ResourceManager.GetString("MessageRetrievePending", resourceCulture);
            }
        }
        
        internal static string FolderIsReadOnly {
            get {
                return ResourceManager.GetString("FolderIsReadOnly", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap ROTopic {
            get {
                object obj = ResourceManager.GetObject("ROTopic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon CixReader {
            get {
                object obj = ResourceManager.GetObject("CixReader", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ActiveStar {
            get {
                object obj = ResourceManager.GetObject("ActiveStar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap InactiveStar {
            get {
                object obj = ResourceManager.GetObject("InactiveStar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Control {
            get {
                object obj = ResourceManager.GetObject("Control", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static string ExpandThread {
            get {
                return ResourceManager.GetString("ExpandThread", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap UnreadPriorityMessage {
            get {
                object obj = ResourceManager.GetObject("UnreadPriorityMessage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static string Normal {
            get {
                return ResourceManager.GetString("Normal", resourceCulture);
            }
        }
        
        internal static string Unignore {
            get {
                return ResourceManager.GetString("Unignore", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Bubble {
            get {
                object obj = ResourceManager.GetObject("Bubble", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static string ManyReplies {
            get {
                return ResourceManager.GetString("ManyReplies", resourceCulture);
            }
        }
        
        internal static string OneReply {
            get {
                return ResourceManager.GetString("OneReply", resourceCulture);
            }
        }
        
        internal static string ResignForum {
            get {
                return ResourceManager.GetString("ResignForum", resourceCulture);
            }
        }
        
        internal static string JoinForum {
            get {
                return ResourceManager.GetString("JoinForum", resourceCulture);
            }
        }
        
        internal static string ConfirmResign {
            get {
                return ResourceManager.GetString("ConfirmResign", resourceCulture);
            }
        }
        
        internal static string IgnoredMessage {
            get {
                return ResourceManager.GetString("IgnoredMessage", resourceCulture);
            }
        }
        
        internal static string Withdraw {
            get {
                return ResourceManager.GetString("Withdraw", resourceCulture);
            }
        }
        
        internal static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        internal static string Reject {
            get {
                return ResourceManager.GetString("Reject", resourceCulture);
            }
        }
        
        internal static string LastOnText {
            get {
                return ResourceManager.GetString("LastOnText", resourceCulture);
            }
        }
        
        internal static string LocationText {
            get {
                return ResourceManager.GetString("LocationText", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Map {
            get {
                object obj = ResourceManager.GetObject("Map", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static string Moderators {
            get {
                return ResourceManager.GetString("Moderators", resourceCulture);
            }
        }
        
        internal static string CannotOpen {
            get {
                return ResourceManager.GetString("CannotOpen", resourceCulture);
            }
        }
        
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        internal static string ConfirmDelete {
            get {
                return ResourceManager.GetString("ConfirmDelete", resourceCulture);
            }
        }
        
        internal static string DeleteFolder {
            get {
                return ResourceManager.GetString("DeleteFolder", resourceCulture);
            }
        }
        
        internal static string NewMessageTitle {
            get {
                return ResourceManager.GetString("NewMessageTitle", resourceCulture);
            }
        }
        
        internal static string ReplyTitle {
            get {
                return ResourceManager.GetString("ReplyTitle", resourceCulture);
            }
        }
        
        internal static string RevertThemeToDefault {
            get {
                return ResourceManager.GetString("RevertThemeToDefault", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Draft {
            get {
                object obj = ResourceManager.GetObject("Draft", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static string OwnerPostingOnly {
            get {
                return ResourceManager.GetString("OwnerPostingOnly", resourceCulture);
            }
        }
        
        internal static string ConfirmWithdraw {
            get {
                return ResourceManager.GetString("ConfirmWithdraw", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Chat {
            get {
                object obj = ResourceManager.GetObject("Chat", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static string XMPPLink {
            get {
                return ResourceManager.GetString("XMPPLink", resourceCulture);
            }
        }
        
        internal static string JoinFailure {
            get {
                return ResourceManager.GetString("JoinFailure", resourceCulture);
            }
        }
        
        internal static string JoinPending {
            get {
                return ResourceManager.GetString("JoinPending", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Error1 {
            get {
                object obj = ResourceManager.GetObject("Error1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Warning {
            get {
                object obj = ResourceManager.GetObject("Warning", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static string ResignPending {
            get {
                return ResourceManager.GetString("ResignPending", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Mail {
            get {
                object obj = ResourceManager.GetObject("Mail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CollapseArrow {
            get {
                object obj = ResourceManager.GetObject("CollapseArrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ExpandArrow {
            get {
                object obj = ResourceManager.GetObject("ExpandArrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static string NoConnection {
            get {
                return ResourceManager.GetString("NoConnection", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Key {
            get {
                object obj = ResourceManager.GetObject("Key", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static string JoinClosed {
            get {
                return ResourceManager.GetString("JoinClosed", resourceCulture);
            }
        }
        
        internal static string DraftText {
            get {
                return ResourceManager.GetString("DraftText", resourceCulture);
            }
        }
        
        internal static string Starred {
            get {
                return ResourceManager.GetString("Starred", resourceCulture);
            }
        }
        
        internal static string MarkFolderRead {
            get {
                return ResourceManager.GetString("MarkFolderRead", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap MarkRead {
            get {
                object obj = ResourceManager.GetObject("MarkRead", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DeleteButton {
            get {
                object obj = ResourceManager.GetObject("DeleteButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static string DeleteConversation {
            get {
                return ResourceManager.GetString("DeleteConversation", resourceCulture);
            }
        }
        
        internal static string Custom {
            get {
                return ResourceManager.GetString("Custom", resourceCulture);
            }
        }
        
        internal static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap MenuDropBlue {
            get {
                object obj = ResourceManager.GetObject("MenuDropBlue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MenuDropWhite {
            get {
                object obj = ResourceManager.GetObject("MenuDropWhite", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CIXLogo2 {
            get {
                object obj = ResourceManager.GetObject("CIXLogo2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static string ReplyEditorTitle {
            get {
                return ResourceManager.GetString("ReplyEditorTitle", resourceCulture);
            }
        }
        
        internal static string LatestVersion {
            get {
                return ResourceManager.GetString("LatestVersion", resourceCulture);
            }
        }
        
        internal static string LatestVersionTitle {
            get {
                return ResourceManager.GetString("LatestVersionTitle", resourceCulture);
            }
        }
        
        internal static string StatusMessagePost {
            get {
                return ResourceManager.GetString("StatusMessagePost", resourceCulture);
            }
        }
        
        internal static string StatusTopicRefresh {
            get {
                return ResourceManager.GetString("StatusTopicRefresh", resourceCulture);
            }
        }
        
        internal static string CustomWords {
            get {
                return ResourceManager.GetString("CustomWords", resourceCulture);
            }
        }
        
        internal static string LinkTooltip {
            get {
                return ResourceManager.GetString("LinkTooltip", resourceCulture);
            }
        }
        
        internal static string UnknownRecipientError {
            get {
                return ResourceManager.GetString("UnknownRecipientError", resourceCulture);
            }
        }
        
        internal static string CopyLinkInfoMessage {
            get {
                return ResourceManager.GetString("CopyLinkInfoMessage", resourceCulture);
            }
        }
        
        internal static string SearchForText {
            get {
                return ResourceManager.GetString("SearchForText", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Search2 {
            get {
                object obj = ResourceManager.GetObject("Search2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static string ScriptException {
            get {
                return ResourceManager.GetString("ScriptException", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap CloseButton {
            get {
                object obj = ResourceManager.GetObject("CloseButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static string SearchForTextIn {
            get {
                return ResourceManager.GetString("SearchForTextIn", resourceCulture);
            }
        }
        
        internal static string StatusInboxRefresh {
            get {
                return ResourceManager.GetString("StatusInboxRefresh", resourceCulture);
            }
        }
        
        internal static string Participants {
            get {
                return ResourceManager.GetString("Participants", resourceCulture);
            }
        }
        
        internal static string CloseSearchBar {
            get {
                return ResourceManager.GetString("CloseSearchBar", resourceCulture);
            }
        }
        
        internal static string CurrentForumSearch {
            get {
                return ResourceManager.GetString("CurrentForumSearch", resourceCulture);
            }
        }
        
        internal static string CurrentTopicSearch {
            get {
                return ResourceManager.GetString("CurrentTopicSearch", resourceCulture);
            }
        }
        
        internal static string ForumsTooltip {
            get {
                return ResourceManager.GetString("ForumsTooltip", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Closed {
            get {
                object obj = ResourceManager.GetObject("Closed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Confidential {
            get {
                object obj = ResourceManager.GetObject("Confidential", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static string Share {
            get {
                return ResourceManager.GetString("Share", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap SmallDownArrow {
            get {
                object obj = ResourceManager.GetObject("SmallDownArrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        internal static string Resign {
            get {
                return ResourceManager.GetString("Resign", resourceCulture);
            }
        }
        
        internal static string SForum {
            get {
                return ResourceManager.GetString("SForum", resourceCulture);
            }
        }
        
        internal static string STopic {
            get {
                return ResourceManager.GetString("STopic", resourceCulture);
            }
        }
        
        internal static string Basic {
            get {
                return ResourceManager.GetString("Basic", resourceCulture);
            }
        }
        
        internal static string Full {
            get {
                return ResourceManager.GetString("Full", resourceCulture);
            }
        }
        
        internal static string Undo {
            get {
                return ResourceManager.GetString("Undo", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap ReadLock {
            get {
                object obj = ResourceManager.GetObject("ReadLock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static string ZipFileExtension {
            get {
                return ResourceManager.GetString("ZipFileExtension", resourceCulture);
            }
        }
        
        internal static string ScriptInstallError {
            get {
                return ResourceManager.GetString("ScriptInstallError", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Script {
            get {
                object obj = ResourceManager.GetObject("Script", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        internal static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        internal static string BadUsernameOrPassword {
            get {
                return ResourceManager.GetString("BadUsernameOrPassword", resourceCulture);
            }
        }
        
        internal static string InactivatedAccount {
            get {
                return ResourceManager.GetString("InactivatedAccount", resourceCulture);
            }
        }
        
        internal static string ReplyToMessage {
            get {
                return ResourceManager.GetString("ReplyToMessage", resourceCulture);
            }
        }
        
        internal static string HideStatusBar {
            get {
                return ResourceManager.GetString("HideStatusBar", resourceCulture);
            }
        }
        
        internal static string ShowStatusBar {
            get {
                return ResourceManager.GetString("ShowStatusBar", resourceCulture);
            }
        }
        
        internal static string AsIgnored {
            get {
                return ResourceManager.GetString("AsIgnored", resourceCulture);
            }
        }
        
        internal static string AsNormal {
            get {
                return ResourceManager.GetString("AsNormal", resourceCulture);
            }
        }
        
        internal static string AsPriority {
            get {
                return ResourceManager.GetString("AsPriority", resourceCulture);
            }
        }
        
        internal static string AsRead {
            get {
                return ResourceManager.GetString("AsRead", resourceCulture);
            }
        }
        
        internal static string AsUnignored {
            get {
                return ResourceManager.GetString("AsUnignored", resourceCulture);
            }
        }
        
        internal static string AsUnread {
            get {
                return ResourceManager.GetString("AsUnread", resourceCulture);
            }
        }
        
        internal static string ClearFlag {
            get {
                return ResourceManager.GetString("ClearFlag", resourceCulture);
            }
        }
        
        internal static string ClearReadLock {
            get {
                return ResourceManager.GetString("ClearReadLock", resourceCulture);
            }
        }
        
        internal static string Flag {
            get {
                return ResourceManager.GetString("Flag", resourceCulture);
            }
        }
        
        internal static string SetReadLock {
            get {
                return ResourceManager.GetString("SetReadLock", resourceCulture);
            }
        }
        
        internal static string PrintError {
            get {
                return ResourceManager.GetString("PrintError", resourceCulture);
            }
        }
        
        internal static string PrintMailDate {
            get {
                return ResourceManager.GetString("PrintMailDate", resourceCulture);
            }
        }
        
        internal static string PrintMailFrom {
            get {
                return ResourceManager.GetString("PrintMailFrom", resourceCulture);
            }
        }
        
        internal static string PrintMailSubject {
            get {
                return ResourceManager.GetString("PrintMailSubject", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap SmartFolder {
            get {
                object obj = ResourceManager.GetObject("SmartFolder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static string NoSignature {
            get {
                return ResourceManager.GetString("NoSignature", resourceCulture);
            }
        }
        
        internal static string ParticipantsCount {
            get {
                return ResourceManager.GetString("ParticipantsCount", resourceCulture);
            }
        }
        
        internal static string ParticipantsTitle {
            get {
                return ResourceManager.GetString("ParticipantsTitle", resourceCulture);
            }
        }
        
        internal static string SearchWith {
            get {
                return ResourceManager.GetString("SearchWith", resourceCulture);
            }
        }
        
        internal static string SearchEngines {
            get {
                return ResourceManager.GetString("SearchEngines", resourceCulture);
            }
        }
        
        internal static string OutboxText {
            get {
                return ResourceManager.GetString("OutboxText", resourceCulture);
            }
        }
        
        internal static string DeleteOnMenu {
            get {
                return ResourceManager.GetString("DeleteOnMenu", resourceCulture);
            }
        }
        
        internal static string GotoError {
            get {
                return ResourceManager.GetString("GotoError", resourceCulture);
            }
        }
        
        internal static string WithdrawOnMenu {
            get {
                return ResourceManager.GetString("WithdrawOnMenu", resourceCulture);
            }
        }
        
        internal static string JoinForumStatusText {
            get {
                return ResourceManager.GetString("JoinForumStatusText", resourceCulture);
            }
        }
        
        internal static string JoinClosedForum {
            get {
                return ResourceManager.GetString("JoinClosedForum", resourceCulture);
            }
        }
        
        internal static string RequestAdmittance {
            get {
                return ResourceManager.GetString("RequestAdmittance", resourceCulture);
            }
        }
        
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        internal static string JoinNoSuchForum {
            get {
                return ResourceManager.GetString("JoinNoSuchForum", resourceCulture);
            }
        }
        
        internal static string HideToolBar {
            get {
                return ResourceManager.GetString("HideToolBar", resourceCulture);
            }
        }
        
        internal static string ShowToolBar {
            get {
                return ResourceManager.GetString("ShowToolBar", resourceCulture);
            }
        }
        
        internal static string Directory {
            get {
                return ResourceManager.GetString("Directory", resourceCulture);
            }
        }
        
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        internal static string SearchIn {
            get {
                return ResourceManager.GetString("SearchIn", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap CIXReaderLogo {
            get {
                object obj = ResourceManager.GetObject("CIXReaderLogo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ChristmasLogo {
            get {
                object obj = ResourceManager.GetObject("ChristmasLogo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static string ManageForum {
            get {
                return ResourceManager.GetString("ManageForum", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap ManageGeneral {
            get {
                object obj = ResourceManager.GetObject("ManageGeneral", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ManageMods {
            get {
                object obj = ResourceManager.GetObject("ManageMods", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ManageParts {
            get {
                object obj = ResourceManager.GetObject("ManageParts", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static string ClosedForum {
            get {
                return ResourceManager.GetString("ClosedForum", resourceCulture);
            }
        }
        
        internal static string OpenForum {
            get {
                return ResourceManager.GetString("OpenForum", resourceCulture);
            }
        }
        
        internal static string PrivateForum {
            get {
                return ResourceManager.GetString("PrivateForum", resourceCulture);
            }
        }
        
        internal static string RemoveButton {
            get {
                return ResourceManager.GetString("RemoveButton", resourceCulture);
            }
        }
        
        internal static string RestoreButton {
            get {
                return ResourceManager.GetString("RestoreButton", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap GeneralPrefImage {
            get {
                object obj = ResourceManager.GetObject("GeneralPrefImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SignaturePreferences {
            get {
                object obj = ResourceManager.GetObject("SignaturePreferences", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap UpdatePreferences {
            get {
                object obj = ResourceManager.GetObject("UpdatePreferences", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ViewingPrefImage {
            get {
                object obj = ResourceManager.GetObject("ViewingPrefImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static string Daily {
            get {
                return ResourceManager.GetString("Daily", resourceCulture);
            }
        }
        
        internal static string Never {
            get {
                return ResourceManager.GetString("Never", resourceCulture);
            }
        }
        
        internal static string Weekly {
            get {
                return ResourceManager.GetString("Weekly", resourceCulture);
            }
        }
        
        internal static string CustomiseToolbar {
            get {
                return ResourceManager.GetString("CustomiseToolbar", resourceCulture);
            }
        }
        
        internal static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap SmallFolder {
            get {
                object obj = ResourceManager.GetObject("SmallFolder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static string AllCategories {
            get {
                return ResourceManager.GetString("AllCategories", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Inbox {
            get {
                object obj = ResourceManager.GetObject("Inbox", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static string NewPMessage {
            get {
                return ResourceManager.GetString("NewPMessage", resourceCulture);
            }
        }
        
        internal static string NoSubject {
            get {
                return ResourceManager.GetString("NoSubject", resourceCulture);
            }
        }
        
        internal static string OnlineUsers {
            get {
                return ResourceManager.GetString("OnlineUsers", resourceCulture);
            }
        }
        
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        internal static string InboxName {
            get {
                return ResourceManager.GetString("InboxName", resourceCulture);
            }
        }
        
        internal static string PMessagesTooltip {
            get {
                return ResourceManager.GetString("PMessagesTooltip", resourceCulture);
            }
        }
        
        internal static string DirectoryTooltip {
            get {
                return ResourceManager.GetString("DirectoryTooltip", resourceCulture);
            }
        }
        
        internal static string Beta {
            get {
                return ResourceManager.GetString("Beta", resourceCulture);
            }
        }
        
        internal static string BetaTooltip {
            get {
                return ResourceManager.GetString("BetaTooltip", resourceCulture);
            }
        }
        
        internal static string Support {
            get {
                return ResourceManager.GetString("Support", resourceCulture);
            }
        }
        
        internal static string SupportTooltip {
            get {
                return ResourceManager.GetString("SupportTooltip", resourceCulture);
            }
        }
        
        internal static string TopThreads {
            get {
                return ResourceManager.GetString("TopThreads", resourceCulture);
            }
        }
        
        internal static string WelcomeSubtitle {
            get {
                return ResourceManager.GetString("WelcomeSubtitle", resourceCulture);
            }
        }
        
        internal static string WelcomeTitle {
            get {
                return ResourceManager.GetString("WelcomeTitle", resourceCulture);
            }
        }
        
        internal static string StartedAt {
            get {
                return ResourceManager.GetString("StartedAt", resourceCulture);
            }
        }
        
        internal static string StartedBy {
            get {
                return ResourceManager.GetString("StartedBy", resourceCulture);
            }
        }
        
        internal static string RefreshText {
            get {
                return ResourceManager.GetString("RefreshText", resourceCulture);
            }
        }
        
        internal static string BlockPrompt {
            get {
                return ResourceManager.GetString("BlockPrompt", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap rulesPreferences {
            get {
                object obj = ResourceManager.GetObject("rulesPreferences", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static string BlockTitle {
            get {
                return ResourceManager.GetString("BlockTitle", resourceCulture);
            }
        }
        
        internal static string ResetRules {
            get {
                return ResourceManager.GetString("ResetRules", resourceCulture);
            }
        }
        
        internal static string ResetRulesTitle {
            get {
                return ResourceManager.GetString("ResetRulesTitle", resourceCulture);
            }
        }
        
        internal static string Operator {
            get {
                return ResourceManager.GetString("Operator", resourceCulture);
            }
        }
        
        internal static string Property {
            get {
                return ResourceManager.GetString("Property", resourceCulture);
            }
        }
        
        internal static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        internal static string MarkAllRead {
            get {
                return ResourceManager.GetString("MarkAllRead", resourceCulture);
            }
        }
        
        internal static string MarkAllReadPrompt {
            get {
                return ResourceManager.GetString("MarkAllReadPrompt", resourceCulture);
            }
        }
        
        internal static string SyncMessage {
            get {
                return ResourceManager.GetString("SyncMessage", resourceCulture);
            }
        }
        
        internal static string StatusMessagePosted {
            get {
                return ResourceManager.GetString("StatusMessagePosted", resourceCulture);
            }
        }
        
        internal static string StatusMessagePosting {
            get {
                return ResourceManager.GetString("StatusMessagePosting", resourceCulture);
            }
        }
        
        internal static string StartRefresh {
            get {
                return ResourceManager.GetString("StartRefresh", resourceCulture);
            }
        }
        
        internal static string StopRefresh {
            get {
                return ResourceManager.GetString("StopRefresh", resourceCulture);
            }
        }
    }
}
